spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.102:8848
    alicloud:
      access-key: LTAI4G56gKd3TvHgFnumVVGk
      secret-key: x25I5NYT3Ut4vzE5t0c0L2AS28qywW
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com
        bucket: gulimall-hellowordjava
  application:
    name: gulimall-third-party
server:
  port: 30000
